### PR TITLE
fix: Add identifier and schema to `get_relation_last_modified` macro

### PR DESCRIPTION
**Pull request by xcezz**
### Summary

The `get_relation_last_modified` macro currently returns an invalid data structure, causing compilation errors when running `dbt source freshness`.

This PR adds identifier and schema columns and keeps the existing data structure expected by dbt.

### Description

After updating `dbt` and `dbt-dremio` from 1.7 to 1.8, I noticed that freshness checks no longer work:

```bash
20:41:23    Compilation Error in source <SOURCE> (models/sources.yml)
  Got an invalid result from "get_relation_last_modified" macro: [(datetime.datetime(2025, 1, 31, 20, 13, 6), datetime.datetime(2025, 1, 31, 20, 41, 22))]
```

After reading https://github.com/dbt-labs/dbt-core/discussions/8307, especially looking at the `get_relation_last_modified` [reference implementation](https://github.com/dbt-labs/dbt-snowflake/blob/cf854b5c1c9b6b8e9b84e77c4f27b4ede3fc47df/dbt/include/snowflake/macros/metadata.sql) from Snowflake, I noticed we don't return 

- `schema` and
- `identifier`

With this change, `dbt source freshness` returns proper freshness information without compilation errors.

### Changelog

-   [ ] Added a summary of what this PR accomplishes to CHANGELOG.md

### CODE REVIEW

**Comment by howareyouman** [comment]
@xcezz Hey! 
Thank you for your contribution!
Before merging this PR, please sign [Contributor License Agreement](https://www.dremio.com/legal/contributor-agreement/), enabling Dremio to distribute your contribution without restriction. 
Thank you beforehand!

**Comment by wobu** [comment]
some additional context: 
in this dbt-adapters PR: https://github.com/dbt-labs/dbt-adapters/pull/127
they introduces the usage and requirement of the 'schema' and 'identifier' field

**Review by bcmeireles — COMMENTED** [review]
Thanks for the contribution!
I see in this PR's [CI run ](https://github.com/dremio/dbt-dremio/actions/runs/13136623948/job/36664635868?pr=274) that this actually solves one of our known failures in the tests. Could you also please update [`.github/expected_failures`](https://github.com/dremio/dbt-dremio/blob/main/.github/expected_failures.txt) by removing:
```
tests/functional/adapter/relation/test_get_relation_last_modified.py::TestGetLastRelationModified::test_get_last_relation_modified
``` 


Thanks :)

**Comment by howareyouman** [comment]
@xcezz Hey! Have you already signed CLA? Our colleagues haven't received any new CLA signs yet.

**Comment by xcezz** [comment]
> @xcezz Hey! Have you already signed CLA? Our colleagues haven't received any new CLA signs yet.

I thought I had already done that. I've just signed it again!

**Review by bcmeireles — APPROVED** [review]

**Review by howareyouman — APPROVED** [review]
