### ISSUE TITLE
[Bug]: Raw reflection config options throws 'dict object' has no attribute 'CompilationError'

### ISSUE THREAD

**Issue by wilso** [dremio/dbt-dremio#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding `{{ config(materialized = 'reflection', reflection_type = 'raw') }}` to the top of a sql model to try and configure a raw reflection on a VDS the following error is thrown:
> 20:04:56  Compilation Error in model my_second_dbt_model (models/example/my_second_dbt_model.sql)
> 20:04:56    'dict object' has no attribute 'CompilationError'

I'm able to reproduce this with our internal dbt repo and with the example models from `dbt init`.

### Expected Behavior

Reflection gets created on VDS.

### Steps To Reproduce

1. Create new dbt project with `dbt init`
2. `dbt run` to apply example models
3. Add `{{ config(materialized = 'reflection', reflection_type = 'raw') }}` to the top of `models/example/my_second_dbt_model.sql`.
4. `dbt run` will throw error:
>20:18:18  Compilation Error in model my_second_dbt_model (models/example/my_second_dbt_model.sql)
>20:18:18    'dict object' has no attribute 'CompilationError'

### Environment

```markdown
- OS: macOS Big Sur 11.7.7
- dbt-dremio: 1.4.5, 1.5.0
- Dremio Software: 23.1.40(AWS Edition), 24.1.0(Community Edition)
- Dremio Cloud: N/A
```

### Relevant log output

```shell
20:18:17  Running with dbt=1.4.5
20:18:17  Found 2 models, 4 tests, 0 snapshots, 0 analyses, 333 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics
20:18:17
20:18:18  Concurrency: 4 threads (target='dbt-dremio')
20:18:18
20:18:18  1 of 2 START sql table model $scratch.my_first_dbt_model ....................... [RUN]
20:18:18  1 of 2 OK created sql table model $scratch.my_first_dbt_model .................. [2 in 0.55s]
20:18:18  2 of 2 START sql reflection model my_second_dbt_model .......................... [RUN]
20:18:18  2 of 2 ERROR creating sql reflection model my_second_dbt_model ................. [ERROR in 0.05s]
20:18:18
20:18:18  Finished running 1 table model, 1 reflection model in 0 hours 0 minutes and 1.38 seconds (1.38s).
20:18:18
20:18:18  Completed with 1 error and 0 warnings:
20:18:18
20:18:18  Compilation Error in model my_second_dbt_model (models/example/my_second_dbt_model.sql)
20:18:18    'dict object' has no attribute 'CompilationError'
20:18:18
20:18:18  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
```

**Comment by wilso** [comment]
It looks like this works with `dbt-core==1.3.2` and `dbt-dremio==1.3.2` but not with any newer version of dbt-core or dbt-dremio.

**Comment by donatobarone** [comment]
I get the exact same error. I have dbt-core 1.5.2 and 1.5.0

**Comment by donatobarone** [comment]
Okay I got a bit further here, in order to create the reflection theoretically, but I might be wrong :D you would have to create a separate model which the only macro is calling is the one you have, but you will have to specify the dependency from the original view model using the --depends_on comment, as explained in the wiki https://github.com/dremio/dbt-dremio/wiki/Using-Materializations-with-Dremio#configuring-reflections. Maybe they have changed the workflow to create reflections. Still that failed, because either I am doing something wrong or the macro has a bug. Will create a ticket for it.

**Comment by ravjotbrar** [comment]
Apologies for the delayed response. What happens if you add this to the bottom of your dbt_project.yml file:
```
vars:
  dremio:reflections_enabled: true
```

**Comment by mxmarg** [comment]
Setting `vars` seems to solve the issue in my case.
Can we maybe add a more descriptive error message and better documentation in the wiki around the importance of setting this flag in the `project.yml`?
